services:
  postgres:
    image: postgres:15
    container_name: historian_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: historian
      POSTGRES_USER: historian
      POSTGRES_PASSWORD: historian
    ports:
      - "5432:5432"
    volumes:
      - pg_data_dev:/var/lib/postgresql/data
    networks:
      - historian_network_dev

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: historian_app_dev
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://historian:historian@postgres:5432/historian
      - DATABASE_URL_UNPOOLED=postgres://historian:historian@postgres:5432/historian
      - PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ../:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "npx prisma db push --accept-data-loss && npm run dev"
    networks:
      - historian_network_dev

volumes:
  pg_data_dev:

networks:
  historian_network_dev:
